AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the prometheus helm chart into an existing kubernetes cluster (qs-1qde66ffn)"
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  ClusterName:
    Type: String
Resources:
  # Install prometheus helm chart
  PrometheusHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref ClusterName
      Namespace: prometheus
      Chart: stable/prometheus
      Name: prometheus
      Values:
        server.persistentVolume.storageClass: "gp2"
        server.statefulSet.enabled: true
        server.replicaCount: 2
        server.service.sessionAffinity: ClientIP
        alertmanager.persistentVolume.storageClass: "gp2"
        alertmanager.statefulSet.enabled: true
        alertmanager.replicaCount: 2
Outputs:
  PrometheusReleaseName:
    Value: !Ref PrometheusHelmChart
