project:
  name: quickstart-amazon-eks
  owner: quickstart-eng@amazon.com
  regions:
  - ap-east-1
  - ap-northeast-1
  - ap-south-1
  - ap-southeast-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  template: templates/amazon-eks-master.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    BastionHostHelmVersion: Helm3
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ProvisionBastionHost: Disabled
  public-endpoint:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-northeast-2
  with-bastion:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
    regions:
      - us-west-2
  cluster-autoscaler:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - eu-central-1
  efs:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EfsStorageClass: Enabled
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      ProvisionBastionHost: Disabled
    regions:
    - eu-north-1
  efs-prov:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EfsStorageClass: Enabled
      ClusterAutoScaler: Disabled
      EfsThroughputMode: provisioned
      EfsProvisionedThroughputInMibps: 100
    regions:
    - us-east-2
  managed-node-group:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      ProvisionBastionHost: Disabled
    regions:
    - us-east-1
  monitoring-prom-graf:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      MonitoringStack: Prometheus + Grafana
    regions:
    - ap-southeast-2
    - us-west-2
  2az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
    regions:
    - ca-central-1
    - cn-north-1
  no-logging:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSClusterLoggingTypes: ""
      ProvisionBastionHost: Disabled
    regions:
      - eu-west-1
  with-hybrid:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Disabled
      ManagedNodeGroup: 'yes'
      ManagedNodeGroupAMIType: AL2_x86_64
      MangedNodeGroupLabel: TestMNG
    regions:
    - us-west-2
  alb-ingress:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ALBIngressController: Enabled
    regions:
    - us-east-2
  fargate:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      FargateNamespaces: kube-system
      FargateLabels: 'app.kubernetes.io/name=aws-cluster-autoscaler'
    regions:
    - us-east-1