AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy KubeSphere into a new EKS cluster in a new VPC (qs-1pipr93g1)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - AvailabilityZones
      - VPCCIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PrivateSubnet3CIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR
      - RemoteAccessCIDR
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - KeyPairName
    - Label:
        default: EKS configuration
      Parameters:
      - NodeInstanceType
      - NumberOfNodes
      - NodeGroupName
      - NodeVolumeSize
      - AdditionalEKSAdminArns
      - KubernetesVersion
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
      - QSS3BucketRegion
      - LambdaZipsBucketName
    - Label:
        default: KubeSphere Quick Start True/False configuration
      Parameters:
      - Openpitrix  
      - Devops
      - Servicemesh
      - Notification
      - Alerting
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      AdditionalEKSAdminArns:
        default: Additional EKS admin ARN's
      LambdaZipsBucketName:
        default: Lambda zips bucket name
      KubernetesVersion:
        default: Kubernetes version
      #KubeSphereLicenseKey:
      #  default: KubeSphere license key
      
Resources:
  KubeSphereStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://quickstart-eks-kubesphere.s3.us-east-2.amazonaws.com/ks/templates/KubeSphere-enable.template.yaml'
      Parameters:
        KubeManifestLambdaArn: "arn:aws:lambda:us-east-2:584003659997:function:kubesphere0222-EKSStack-CO3JZ8I-KubeManifestLambda-HBVD4CPXE1R7"
        KubeConfigPath: "s3://kubesphere0222-eksstack-co3jz8iy-kubeconfigbucket-bstyy55m9byz/.kube/config.enc"
        KubeConfigKmsContext: "EKSQuickStart"
        KubeClusterName: "EKS-e8bB5Q1WhMaG"
        Openpitrix: false
        Devops: false
        Servicemesh: false
        Notification: true
        Alerting: false
        #KubeSphereLicenseKey: !Ref KubeSphereLicenseKey

Outputs:
  KubeSphereConsoleEndpoint:
    Value: !GetAtt KubeSphereStack.Outputs.KubeSphereConsole
